# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

networks:
  production-network:
    driver:
      nat

services:
  webapi:
    container_name: webapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    networks:
      - production-network
    image: webapi:v1